In [ ]:
import pandas as pd
import numpy as np
from geopy.geocoders import GoogleV3
import re

In [ ]:
pd.set_option('display.max_columns', None)

quantidade_nans_por_coluna = dados.isna().sum()

In [ ]:
#organizar isso

**Visualizar o dataframe, checar quantidade de colunas com valores fixos(mesmo valor da coluna para todos os registros) e checar para valores nan presentes. Atencao que valores nan unicos para uma mesma coluna nos diversos registros vao ser, primeiro, descobertos no processo de checagem de valores fixos**

In [ ]:
dados = pd.read_csv('/content/occurrence.txt', engine= 'python', sep='        ') #separador utilizado na formatação do arquivo txt

In [ ]:
dados.head()

gbifID                                       accessRights  \
0  2365686427  Creative Commons Attribution Non Commercial (C...   
1  2365686418  Creative Commons Attribution Non Commercial (C...   
2  2365686416  Creative Commons Attribution Non Commercial (C...   
3  2365686414  Creative Commons Attribution Non Commercial (C...   
4  2365686412  Creative Commons Attribution Non Commercial (C...   

   bibliographicCitation  language       license  modified  publisher  \
0                    NaN       NaN  CC_BY_NC_4_0       NaN        NaN   
1                    NaN       NaN  CC_BY_NC_4_0       NaN        NaN   
2                    NaN       NaN  CC_BY_NC_4_0       NaN        NaN   
3                    NaN       NaN  CC_BY_NC_4_0       NaN        NaN   
4                    NaN       NaN  CC_BY_NC_4_0       NaN        NaN   

   references                         rightsHolder  type  ...  level0Gid  \
0         NaN  Museu Paraense Emílio Goeldi (MPEG)   NaN  ...       None   
1         NaN  Museu Paraense Emílio Goeldi (MPEG)   NaN  ...        BRA   
2         NaN  Museu Paraense Emílio Goeldi (MPEG)   NaN  ...        BRA   
3         NaN  Museu Paraense Emílio Goeldi (MPEG)   NaN  ...       None   
4         NaN  Museu Paraense Emílio Goeldi (MPEG)   NaN  ...       None   

   level0Name  level1Gid level1Name    level2Gid  level2Name  level3Gid  \
0        None       None       None         None        None        NaN   
1      Brazil   BRA.10_1   Maranhão  BRA.10.59_2        Codó        NaN   
2      Brazil   BRA.10_1   Maranhão  BRA.10.52_2      Caxias        NaN   
3        None       None       None         None        None        NaN   
4        None       None       None         None        None        NaN   

  level3Name  iucnRedListCategory  eventType  
0        NaN                 None        NaN  
1        NaN                   NE        NaN  
2        NaN                   NE        NaN  
3        NaN                 None        NaN  
4        NaN                 None        NaN  

[5 rows x 212 columns]

Presença de vários valores NAN

In [ ]:
dados.shape

(892, 212)

892 registros, cada um com 212 colunas

In [ ]:
dados.isna().sum()

gbifID                     0
accessRights               0
bibliographicCitation    892
language                 892
license                    0
                        ... 
level2Name               288
level3Gid                892
level3Name               892
iucnRedListCategory      529
eventType                892
Length: 212, dtype: int64

In [ ]:
(dados.isna().sum() == 0).sum()

24

Apenas 24 colunas estao completas. Ainda tenho que checar se os tipos presentes correspondem a descrição da coluna. Fazer após lidar com os valores nans

Pegar todas as colunas que possuem apenas valores nan, guardar seu nome numa lista e remover do dataframe original. Guardar na lista para poder lidar com esse labels no banco, formatacao exige a presenca delas, mesmo sem dados

In [ ]:
lista_label_colunas_totalmente_nan = []

In [ ]:
quantidade_colunas_totalmente_nan = 0

for column in dados.columns:

  print(column)

  if dados[column].isna().sum() == dados.shape[0]:

    quantidade_colunas_totalmente_nan += 1

    lista_label_colunas_totalmente_nan.append(column)

print(f'quantidade_colunas_totalmente_nan: {quantidade_colunas_totalmente_nan}')

gbifID
accessRights
bibliographicCitation
language
license
modified
publisher
references
rightsHolder
type
institutionID
collectionID
datasetID
institutionCode
collectionCode
datasetName
ownerInstitutionCode
basisOfRecord
informationWithheld
dataGeneralizations
dynamicProperties
occurrenceID
catalogNumber
recordNumber
recordedBy
recordedByID
individualCount
organismQuantity
organismQuantityType
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
degreeOfEstablishment
pathway
georeferenceVerificationStatus
occurrenceStatus
preparations
disposition
associatedOccurrences
associatedReferences
associatedSequences
associatedTaxa
otherCatalogNumbers
occurrenceRemarks
organismID
organismName
organismScope
associatedOrganisms
previousIdentifications
organismRemarks
materialSampleID
eventID
parentEventID
fieldNumber
eventDate
eventTime
startDayOfYear
endDayOfYear
year
month
day
verbatimEventDate
habitat
samplingProtocol
sampleSizeValue
sampleSizeUnit
samplingEffort
fieldNotes
eventRe

In [ ]:
len(lista_label_colunas_totalmente_nan)

145

145 de 212 colunas nao possuem dado nenhum registrado

In [ ]:
dados_sem_colunas_totalmente_nan = dados.drop(lista_label_colunas_totalmente_nan, axis = 1)

In [ ]:
dados_sem_colunas_totalmente_nan.head()

gbifID                                       accessRights  \
0  2365686427  Creative Commons Attribution Non Commercial (C...   
1  2365686418  Creative Commons Attribution Non Commercial (C...   
2  2365686416  Creative Commons Attribution Non Commercial (C...   
3  2365686414  Creative Commons Attribution Non Commercial (C...   
4  2365686412  Creative Commons Attribution Non Commercial (C...   

        license                         rightsHolder institutionCode  \
0  CC_BY_NC_4_0  Museu Paraense Emílio Goeldi (MPEG)            MPEG   
1  CC_BY_NC_4_0  Museu Paraense Emílio Goeldi (MPEG)            MPEG   
2  CC_BY_NC_4_0  Museu Paraense Emílio Goeldi (MPEG)            MPEG   
3  CC_BY_NC_4_0  Museu Paraense Emílio Goeldi (MPEG)            MPEG   
4  CC_BY_NC_4_0  Museu Paraense Emílio Goeldi (MPEG)            MPEG   

  collectionCode       basisOfRecord     occurrenceID    catalogNumber  \
0            ANL  PRESERVED_SPECIMEN  MPEG.ANL 001101  MPEG.ANL 001101   
1            ANL  PRESERVED_SPECIMEN  MPEG.ANL 001596  MPEG.ANL 001596   
2            ANL  PRESERVED_SPECIMEN  MPEG.ANL 001635  MPEG.ANL 001635   
3            ANL  PRESERVED_SPECIMEN  MPEG.ANL 001031  MPEG.ANL 001031   
4            ANL  PRESERVED_SPECIMEN  MPEG.ANL 001036  MPEG.ANL 001036   

                                          recordedBy  ...  \
0          Beckman, Ruana; Pena, José; Souza, Raíssa  ...   
1  Sousa, Sandriel; Hernández, Luis; Rousseau, Gu...  ...   
2      Sousa, Anny; Sousa, Sandriel; Hernández, Luis  ...   
3          Beckman, Ruana; Pena, José; Souza, Raíssa  ...   
4          Beckman, Ruana; Pena, José; Souza, Raíssa  ...   

                 lastParsed               lastCrawled repatriated  level0Gid  \
0  2023-09-07T09:19:05.952Z  2023-01-07T11:25:05.817Z       false       None   
1  2023-09-07T09:19:05.949Z  2023-01-07T11:25:05.817Z       false        BRA   
2  2023-09-07T09:19:05.937Z  2023-01-07T11:25:05.817Z       false        BRA   
3  2023-09-07T09:19:05.946Z  2023-01-07T11:25:05.817Z       false       None   
4  2023-09-07T09:19:05.946Z  2023-01-07T11:25:05.817Z       false       None   

   level0Name  level1Gid level1Name    level2Gid level2Name  \
0        None       None       None         None       None   
1      Brazil   BRA.10_1   Maranhão  BRA.10.59_2       Codó   
2      Brazil   BRA.10_1   Maranhão  BRA.10.52_2     Caxias   
3        None       None       None         None       None   
4        None       None       None         None       None   

  iucnRedListCategory  
0                None  
1                  NE  
2                  NE  
3                None  
4                None  

[5 rows x 67 columns]

In [ ]:
dados_sem_colunas_totalmente_nan.isna().sum()

gbifID                   0
accessRights             0
license                  0
rightsHolder             0
institutionCode          0
                      ... 
level1Gid              288
level1Name             288
level2Gid              288
level2Name             288
iucnRedListCategory    529
Length: 67, dtype: int64

Agora lidar com valores fixos. Depois lidar com os demais nans

Pegar todas as colunas que possuem valor fixo. Guardar o label de cada coluna como uma chave de um dicionario e o valor fixo de dada coluna como o valor associado a chave da label correspondente.

In [ ]:
dicionario_colunas_valores_fixo = {}

In [ ]:
i = 0

for column in dados_sem_colunas_totalmente_nan.columns:

  if len(dados_sem_colunas_totalmente_nan[column].unique()) == 1:

    i += 1

    print(f'Label coluna: {column}')

    print(f'Valor da coluna: {dados_sem_colunas_totalmente_nan[column][0]}\n')

    dicionario_colunas_valores_fixo[column] = [pd.NA, dados_sem_colunas_totalmente_nan[column][0]]

print(i)


Label coluna: accessRights
Valor da coluna: Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.

Label coluna: license
Valor da coluna: CC_BY_NC_4_0

Label coluna: rightsHolder
Valor da coluna: Museu Paraense Emílio Goeldi (MPEG)

Label coluna: institutionCode
Valor da coluna: MPEG

Label coluna: collectionCode
Valor da coluna: ANL

Label coluna: basisOfRecord
Valor da coluna: PRESERVED_SPECIMEN

Label coluna: occurrenceStatus
Valor da coluna: PRESENT

Label coluna: datasetKey
Valor da coluna: 9c48ee0b-404a-4c84-9af0-946eef39ddca

Label coluna: publishingCountry
Valor da coluna: BR

Label coluna: protocol
Valor da coluna: EML

Label coluna: lastCrawled
Valor da coluna: 2023-01-07T11:25:05.817Z

11


In [ ]:
len(dicionario_colunas_valores_fixo)

11

In [ ]:
dicionario_colunas_valores_fixo

{'accessRights': [<NA>,
  'Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.'],
 'license': [<NA>, 'CC_BY_NC_4_0'],
 'rightsHolder': [<NA>, 'Museu Paraense Emílio Goeldi (MPEG)'],
 'institutionCode': [<NA>, 'MPEG'],
 'collectionCode': [<NA>, 'ANL'],
 'basisOfRecord': [<NA>, 'PRESERVED_SPECIMEN'],
 'occurrenceStatus': [<NA>, 'PRESENT'],
 'datasetKey': [<NA>, '9c48ee0b-404a-4c84-9af0-946eef39ddca'],
 'publishingCountry': [<NA>, 'BR'],
 'protocol': [<NA>, 'EML'],
 'lastCrawled': [<NA>, '2023-01-07T11:25:05.817Z']}

In [ ]:
dicionario_colunas_valores_fixo.keys()

dict_keys(['accessRights', 'license', 'rightsHolder', 'institutionCode', 'collectionCode', 'basisOfRecord', 'occurrenceStatus', 'datasetKey', 'publishingCountry', 'protocol', 'lastCrawled'])

In [ ]:
dados_sem_nan_e_fixos = dados_sem_colunas_totalmente_nan.drop(dicionario_colunas_valores_fixo.keys(), axis = 1)

In [ ]:
dados_sem_nan_e_fixos.head()

gbifID     occurrenceID    catalogNumber  \
0  2365686427  MPEG.ANL 001101  MPEG.ANL 001101   
1  2365686418  MPEG.ANL 001596  MPEG.ANL 001596   
2  2365686416  MPEG.ANL 001635  MPEG.ANL 001635   
3  2365686414  MPEG.ANL 001031  MPEG.ANL 001031   
4  2365686412  MPEG.ANL 001036  MPEG.ANL 001036   

                                          recordedBy preparations  \
0          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   
1  Sousa, Sandriel; Hernández, Luis; Rousseau, Gu...   Etanol - 1   
2      Sousa, Anny; Sousa, Sandriel; Hernández, Luis   Etanol - 1   
3          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
4          Beckman, Ruana; Pena, José; Souza, Raíssa  Etanol - 17   

             eventDate    year  month   day eventRemarks  ...  \
0  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
1  2018-08-15T00:00:00  2018.0    8.0  15.0          NaN  ...   
2  2019-02-12T00:00:00  2019.0    2.0  12.0          NaN  ...   
3  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
4  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
0  Pontoscolex Corethrurus  2023-09-07T09:19:05.952Z       false      None   
1        Liodrilus mendesi  2023-09-07T09:19:05.949Z       false       BRA   
2        Liodrilus mendesi  2023-09-07T09:19:05.937Z       false       BRA   
3  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   
4  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   

  level0Name level1Gid  level1Name    level2Gid level2Name iucnRedListCategory  
0       None      None        None         None       None                None  
1     Brazil  BRA.10_1    Maranhão  BRA.10.59_2       Codó                  NE  
2     Brazil  BRA.10_1    Maranhão  BRA.10.52_2     Caxias                  NE  
3       None      None        None         None       None                None  
4       None      None        None         None       None                None  

[5 rows x 56 columns]

Possiveis tratamentos especificos.

In [ ]:
for column in dados_sem_nan_e_fixos:

  if dados_sem_nan_e_fixos[column].isna().sum() > 0:

    print(column)

recordedBy
preparations
eventDate
year
month
day
eventRemarks
higherGeography
continent
countryCode
stateProvince
county
locality
decimalLatitude
decimalLongitude
typeStatus
phylum
class
order
family
genus
genericName
specificEpithet
infraspecificEpithet
taxonomicStatus
acceptedTaxonKey
phylumKey
classKey
orderKey
familyKey
genusKey
speciesKey
species
acceptedScientificName
verbatimScientificName
repatriated
level0Gid
level0Name
level1Gid
level1Name
level2Gid
level2Name
iucnRedListCategory


A

Essas colunas sao explicadas de acordo com a estrutura do gbif, por isso nao tem do dataset em si

In [ ]:
len(dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['eventDate'].isna() & ~dados_sem_nan_e_fixos['day'].isna()])

0

In [ ]:
for valor_campo_data in ['year', 'month', 'day']:


  if len(dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['eventDate'].isna() & ~dados_sem_nan_e_fixos[valor_campo_data].isna()]) > 0:

    print(valor_campo_data)


Nao tem como definir eventDate a partir das colunas year, month e/ou year

In [ ]:
for valor_campo_data in ['year', 'month', 'day']: #sei que é repeticao. Mas separei para deixar mais claro e facilitar a segmentacao da analise


  if len(dados_sem_nan_e_fixos[dados_sem_nan_e_fixos[valor_campo_data].isna() & ~dados_sem_nan_e_fixos['eventDate'].isna()]) > 0:

    print(valor_campo_data)

month
day


Nesse caso, não faz sentido preencher a coluna eventDate com valores arbitrários de ano

In [ ]:
dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['higherGeography'].isna()]

gbifID     occurrenceID    catalogNumber  \
145  2365686000  MPEG.ANL 001044  MPEG.ANL 001044   

                                    recordedBy preparations  \
145  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   

               eventDate    year  month   day eventRemarks  ...  \
145  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
145            Pontoscolex  2023-09-07T09:19:05.946Z        None      None   

    level0Name level1Gid  level1Name  level2Gid level2Name iucnRedListCategory  
145       None      None        None       None       None                None  

[1 rows x 56 columns]

Higher geography é a concatenação das colunas stateProvince e county. Nesse único registro nan para higherGeography, essas duas outras colunas tambem estao faltantes

In [ ]:
dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['continent'].isna()].head()

gbifID     occurrenceID    catalogNumber  \
0  2365686427  MPEG.ANL 001101  MPEG.ANL 001101   
3  2365686414  MPEG.ANL 001031  MPEG.ANL 001031   
4  2365686412  MPEG.ANL 001036  MPEG.ANL 001036   
8  2365686406  MPEG.ANL 001090  MPEG.ANL 001090   
9  2365686405  MPEG.ANL 001083  MPEG.ANL 001083   

                                  recordedBy preparations  \
0  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   
3  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
4  Beckman, Ruana; Pena, José; Souza, Raíssa  Etanol - 17   
8  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
9  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   

             eventDate    year  month   day eventRemarks  ...  \
0  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
3  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
4  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
8  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
9  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
0  Pontoscolex Corethrurus  2023-09-07T09:19:05.952Z       false      None   
3  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   
4  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   
8  Pontoscolex Corethrurus  2023-09-07T09:19:05.947Z       false      None   
9  Pontoscolex Corethrurus  2023-09-07T09:19:05.945Z       false      None   

  level0Name level1Gid  level1Name  level2Gid level2Name iucnRedListCategory  
0       None      None        None       None       None                None  
3       None      None        None       None       None                None  
4       None      None        None       None       None                None  
8       None      None        None       None       None                None  
9       None      None        None       None       None                None  

[5 rows x 56 columns]

In [ ]:
def preencher_continent(row): #Utilizando pares já definidos no dataframe de continente x countryCode, preencher os registros que possuem countryCode preenchido mas continent nao

    if pd.isna(row['continent']):

        valores_conhecidos = dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['countryCode'] == row['countryCode']]['continent'].dropna()

        if not valores_conhecidos.empty:

            return valores_conhecidos.iloc[0]

        else:

            return pd.NA

    else:

        return row['continent']


dados_sem_nan_e_fixos['continent'] = dados_sem_nan_e_fixos.apply(preencher_continent, axis=1)


In [ ]:
dados_sem_nan_e_fixos['continent'] = dados_sem_nan_e_fixos.apply(preencher_continent, axis=1)

In [ ]:
dados_sem_nan_e_fixos.head()

gbifID     occurrenceID    catalogNumber  \
0  2365686427  MPEG.ANL 001101  MPEG.ANL 001101   
1  2365686418  MPEG.ANL 001596  MPEG.ANL 001596   
2  2365686416  MPEG.ANL 001635  MPEG.ANL 001635   
3  2365686414  MPEG.ANL 001031  MPEG.ANL 001031   
4  2365686412  MPEG.ANL 001036  MPEG.ANL 001036   

                                          recordedBy preparations  \
0          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   
1  Sousa, Sandriel; Hernández, Luis; Rousseau, Gu...   Etanol - 1   
2      Sousa, Anny; Sousa, Sandriel; Hernández, Luis   Etanol - 1   
3          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
4          Beckman, Ruana; Pena, José; Souza, Raíssa  Etanol - 17   

             eventDate    year  month   day eventRemarks  ...  \
0  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
1  2018-08-15T00:00:00  2018.0    8.0  15.0          NaN  ...   
2  2019-02-12T00:00:00  2019.0    2.0  12.0          NaN  ...   
3  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
4  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
0  Pontoscolex Corethrurus  2023-09-07T09:19:05.952Z       false      None   
1        Liodrilus mendesi  2023-09-07T09:19:05.949Z       false       BRA   
2        Liodrilus mendesi  2023-09-07T09:19:05.937Z       false       BRA   
3  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   
4  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   

  level0Name level1Gid  level1Name    level2Gid level2Name iucnRedListCategory  
0       None      None        None         None       None                None  
1     Brazil  BRA.10_1    Maranhão  BRA.10.59_2       Codó                  NE  
2     Brazil  BRA.10_1    Maranhão  BRA.10.52_2     Caxias                  NE  
3       None      None        None         None       None                None  
4       None      None        None         None       None                None  

[5 rows x 56 columns]

In [ ]:
dados_sem_nan_e_fixos['continent'].isna().sum()

1

In [ ]:
dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['continent'].isna()]

gbifID     occurrenceID    catalogNumber  \
145  2365686000  MPEG.ANL 001044  MPEG.ANL 001044   

                                    recordedBy preparations  \
145  Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   

               eventDate    year  month   day eventRemarks  ...  \
145  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
145            Pontoscolex  2023-09-07T09:19:05.946Z        None      None   

    level0Name level1Gid  level1Name  level2Gid level2Name iucnRedListCategory  
145       None      None        None       None       None                None  

[1 rows x 56 columns]

In [ ]:
len(dados_sem_nan_e_fixos['continent'].unique()) == 2

True

In [ ]:
dicionario_colunas_valores_fixo['continent'] = [145, dados_sem_nan_e_fixos['continent'][0]]

In [ ]:
dicionario_colunas_valores_fixo #talvez haja a necessidade de salvar os indexes em uma lista aninhada, aguardar pra ver se surge essa necessidade

{'accessRights': [<NA>,
  'Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.'],
 'license': [<NA>, 'CC_BY_NC_4_0'],
 'rightsHolder': [<NA>, 'Museu Paraense Emílio Goeldi (MPEG)'],
 'institutionCode': [<NA>, 'MPEG'],
 'collectionCode': [<NA>, 'ANL'],
 'basisOfRecord': [<NA>, 'PRESERVED_SPECIMEN'],
 'occurrenceStatus': [<NA>, 'PRESENT'],
 'datasetKey': [<NA>, '9c48ee0b-404a-4c84-9af0-946eef39ddca'],
 'publishingCountry': [<NA>, 'BR'],
 'protocol': [<NA>, 'EML'],
 'lastCrawled': [<NA>, '2023-01-07T11:25:05.817Z'],
 'continent': [145, 'SOUTH_AMERICA']}

In [ ]:
dados_sem_nan_e_fixos = dados_sem_nan_e_fixos.drop('continent', axis = 1)

In [ ]:
dados_sem_nan_e_fixos.head()

gbifID     occurrenceID    catalogNumber  \
0  2365686427  MPEG.ANL 001101  MPEG.ANL 001101   
1  2365686418  MPEG.ANL 001596  MPEG.ANL 001596   
2  2365686416  MPEG.ANL 001635  MPEG.ANL 001635   
3  2365686414  MPEG.ANL 001031  MPEG.ANL 001031   
4  2365686412  MPEG.ANL 001036  MPEG.ANL 001036   

                                          recordedBy preparations  \
0          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   
1  Sousa, Sandriel; Hernández, Luis; Rousseau, Gu...   Etanol - 1   
2      Sousa, Anny; Sousa, Sandriel; Hernández, Luis   Etanol - 1   
3          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
4          Beckman, Ruana; Pena, José; Souza, Raíssa  Etanol - 17   

             eventDate    year  month   day eventRemarks  ...  \
0  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
1  2018-08-15T00:00:00  2018.0    8.0  15.0          NaN  ...   
2  2019-02-12T00:00:00  2019.0    2.0  12.0          NaN  ...   
3  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   
4  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN  ...   

    verbatimScientificName                lastParsed repatriated level0Gid  \
0  Pontoscolex Corethrurus  2023-09-07T09:19:05.952Z       false      None   
1        Liodrilus mendesi  2023-09-07T09:19:05.949Z       false       BRA   
2        Liodrilus mendesi  2023-09-07T09:19:05.937Z       false       BRA   
3  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   
4  Pontoscolex Corethrurus  2023-09-07T09:19:05.946Z       false      None   

  level0Name  level1Gid  level1Name    level2Gid level2Name  \
0       None       None        None         None       None   
1     Brazil   BRA.10_1    Maranhão  BRA.10.59_2       Codó   
2     Brazil   BRA.10_1    Maranhão  BRA.10.52_2     Caxias   
3       None       None        None         None       None   
4       None       None        None         None       None   

  iucnRedListCategory  
0                None  
1                  NE  
2                  NE  
3                None  
4                None  

[5 rows x 55 columns]

Como é apenas 1 registro de 892 que possui valor nan (e diferente do fixo) para essa coluna. Jogar essa coluna no dicionario. Dropar ela. Salvar o index do registro nan.

In [ ]:
'''countryCode
stateProvince
county
higherGeography''' '''checar se posso compeltar um a partir do outro'''

'countryCode\nstateProvince\ncounty\nhigherGeographychecar se posso compeltar um a partir do outro'

In [ ]:
dados_sem_nan_e_fixos['higherGeography'].isna().sum()

1

In [ ]:
dados_sem_nan_e_fixos['stateProvince'].isna().sum()

1

In [ ]:
dados_sem_nan_e_fixos['county'].isna().sum()

27

In [ ]:
dados_sem_nan_e_fixos[dados_sem_nan_e_fixos['county'].isna()][['stateProvince', 'county', 'higherGeography']]

stateProvince county higherGeography
10           Pará    NaN            Pará
33           Pará    NaN            Pará
69           Pará    NaN            Pará
128          Pará    NaN            Pará
145           NaN    NaN             NaN
173          Pará    NaN            Pará
301          Pará    NaN            Pará
311          Pará    NaN            Pará
375          Pará    NaN            Pará
533   Mato Grosso    NaN     Mato Grosso
538   Mato Grosso    NaN     Mato Grosso
542          Pará    NaN            Pará
543          Pará    NaN            Pará
544   Mato Grosso    NaN     Mato Grosso
545          Pará    NaN            Pará
549          Pará    NaN            Pará
551   Mato Grosso    NaN     Mato Grosso
555          Pará    NaN            Pará
556   Mato Grosso    NaN     Mato Grosso
557          Pará    NaN            Pará
560          Pará    NaN            Pará
561          Pará    NaN            Pará
562          Pará    NaN            Pará
570          Pará    NaN            Pará
579   Mato Grosso    NaN     Mato Grosso
665          Pará    NaN            Pará
697          Pará    NaN            Pará

Nao tem como definir os valores faltantes da coluna county a partir da coluna higherGeography. Quando a coluna county está faltante, a coluna higherGeography possui apenas o estado como valor

In [ ]:
#tomar cuidado com os 'incertos' podem fuder o role

In [ ]:
dados_sem_nan_e_fixos['acceptedScientificName'].unique()

array(['Pontoscolex', 'Liodrilus mendesi Righi, 1994',
       'Heteromastus Eisig, 1887',
       'Pontoscolex corethrurus (Muller, 1856)',
       'Laeonereis culveri (Webster, 1879)', nan,
       'Neanthes Kinberg, 1865',
       'Rhinodrilus antonioi Hernández-García & Sousa, 2020',
       'Hyperiodrilus africanus Beddard, 1891',
       'Sigambra grubii Müller, 1858', 'Capitella Blainville, 1828',
       'Laeonereis Hartman, 1945', 'Nephtys fluviatilis Monro, 1937',
       'Righiodrilus tocantinensis (Righi, 1972)',
       'Sigambra Müller, 1858', 'Notomastus M.Sars, 1851',
       'Aphrodita Linnaeus, 1758', 'Urobenus petrerei Righi, 1985',
       'Benhamia affinis Michaelsen, 1890',
       'Dichogaster bolaui (Michaelsen, 1891)',
       'Phragmatopoma caudata Krøyer, 1863', 'Namalycastis Hartman, 1959',
       'Nereis Linnaeus, 1758', 'Clitellata',
       'Rhinodrilus brasiliensis (Benham, 1886)',
       'Aglaophamus Kinberg, 1866', 'Lumbriculidae', 'Terebellidae',
       'Naididae', 

In [ ]:
campos_taxonomicos = ['typeStatus', 'phylum', 'class', 'order', 'family', 'genus', 'genericName', 'specificEpithet',
'infraspecificEpithet', 'taxonomicStatus', 'acceptedTaxonKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey',
'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName']

In [ ]:
dados_sem_nan_e_fixos[campos_taxonomicos].isna().sum().sum()

6545

In [ ]:
def preencher_campos_taxonomicos(row): #talvez de pra otimizar sem precisar do loop (sem precisar nomear cada coluna para testar individualmente!!)

  for campo_taxonomico in campos_taxonomicos:

    if pd.isna(row[campo_taxonomico]):

      # Filtra o DataFrame para registros correspondentes
            registro_correspondente = dados_sem_nan_e_fixos[
                (dados_sem_nan_e_fixos[campo_taxonomico].notna()) &
                (dados_sem_nan_e_fixos['acceptedScientificName'] == row['acceptedScientificName'])
            ]

            if not registro_correspondente.empty:

              # Preenche com o valor do registro correspondente
              valor_preenchimento = registro_correspondente.iloc[0][campo_taxonomico]
              row[campo_taxonomico] = valor_preenchimento


    return row


In [ ]:
dados_sem_nan_e_fixos = dados_sem_nan_e_fixos.apply(preencher_campos_taxonomicos, axis = 1)

In [ ]:
dados_sem_nan_e_fixos[campos_taxonomicos].isna().sum().sum()

6384

Definir municipios nan de acordo com valores de latitude e longitude. Lembrar que esses valores decimais sao arredondados

In [ ]:
api_key = 'AIzaSyA1i2SfD6tG3WaEQ2ap3caURfWSqdkMGVA'

In [ ]:
geolocator = GoogleV3(api_key=api_key)

In [ ]:
padrao = re.compile(r',\s*([^,-]*)(?:\s*-\s*|$)')

In [ ]:
dados_sem_nan_e_fixos['county'].isna().sum()

27

In [ ]:
dados_sem_nan_e_fixos['locality'].isna().sum()

1

In [ ]:
def definir_campos_localizacao(row):

  latitude = row['decimalLatitude']

  longitude = row['decimalLongitude']

  if (pd.isna(longitude) or pd.isna(latitude)) or not pd.isna(row['county']):

    return row

  location = geolocator.reverse((latitude, longitude), exactly_one=True)

  cidade =  padrao.search(location[0])

  if cidade:

    row['county'] = cidade.group(1).strip()

    print(row['county'])

  return row


In [ ]:
dados_sem_nan_e_fixos = dados_sem_nan_e_fixos.apply(definir_campos_localizacao, axis = 1)

Conceição do Araguaia


In [ ]:
dados_sem_nan_e_fixos['county'].isna().sum()

26

A maioria dos registros que não possuem localização de municipio, foram registrados em mar aberto

# ***Utilizar os dados abaixo:***

145 das colunas não possuem nenhuma informação- em nenhum dos registros. Coloquei em uma lista pois vão ter que estar presentes no banco de dados por causa da exigencia da estrutura do gbif. Nesse caso, criar uma table separada para colocar um registro, tendo label de cada umas colunas como valor de um campo dessa table. Utilizar uma view (com transpose) para facilitar a concatenação dessas colunas sem informação junto com as demais para garantir a estrutura exigida pelo gbif.

12 das colunas possuem valores fixos próprios para todos os registros. Coloquei em um dicionário para associar label de cada uma dessas colunas com o valor fixo delas para os registros. Além do valor fixo, o valor associado a cada chave possui também um elemento a mais: o indice do registro que possui qualquer variação em relação ao valor fixo. Ou seja, cada chave está associada a uma lista de 2 elementos [indice da excecao, valor fixo para a coluna]. O valor exceção é sempre um NaN (sem informacao nenhuma). Nesse caso, criar uma table separa para colocar associacao entre registros, excecao e valor fixo. Utilizar uma view (com transpose) para facilitar a concatenação dessas colunas fixas junto com as demais para garantir a estrutura exigida pelo gbif.

Em relação a normalização, atenção pois as colunas referentes a localização do registro possuem redundancia. Decidir quais utilizar no power bi.

In [ ]:
dicionario_colunas_valores_fixo

{'accessRights': [<NA>,
  'Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.'],
 'license': [<NA>, 'CC_BY_NC_4_0'],
 'rightsHolder': [<NA>, 'Museu Paraense Emílio Goeldi (MPEG)'],
 'institutionCode': [<NA>, 'MPEG'],
 'collectionCode': [<NA>, 'ANL'],
 'basisOfRecord': [<NA>, 'PRESERVED_SPECIMEN'],
 'occurrenceStatus': [<NA>, 'PRESENT'],
 'datasetKey': [<NA>, '9c48ee0b-404a-4c84-9af0-946eef39ddca'],
 'publishingCountry': [<NA>, 'BR'],
 'protocol': [<NA>, 'EML'],
 'lastCrawled': [<NA>, '2023-01-07T11:25:05.817Z'],
 'continent': [145, 'SOUTH_AMERICA']}

In [ ]:
lista_label_colunas_totalmente_nan

['bibliographicCitation',
 'language',
 'modified',
 'publisher',
 'references',
 'type',
 'institutionID',
 'collectionID',
 'datasetID',
 'datasetName',
 'ownerInstitutionCode',
 'informationWithheld',
 'dataGeneralizations',
 'dynamicProperties',
 'recordNumber',
 'recordedByID',
 'individualCount',
 'organismQuantity',
 'organismQuantityType',
 'sex',
 'lifeStage',
 'reproductiveCondition',
 'behavior',
 'establishmentMeans',
 'degreeOfEstablishment',
 'pathway',
 'georeferenceVerificationStatus',
 'disposition',
 'associatedOccurrences',
 'associatedReferences',
 'associatedSequences',
 'associatedTaxa',
 'otherCatalogNumbers',
 'occurrenceRemarks',
 'organismID',
 'organismName',
 'organismScope',
 'associatedOrganisms',
 'previousIdentifications',
 'organismRemarks',
 'materialSampleID',
 'eventID',
 'parentEventID',
 'fieldNumber',
 'eventTime',
 'startDayOfYear',
 'endDayOfYear',
 'verbatimEventDate',
 'habitat',
 'samplingProtocol',
 'sampleSizeValue',
 'sampleSizeUnit',
 'sa

In [ ]:
dados_sem_nan_e_fixos.head()

gbifID     occurrenceID    catalogNumber  \
0  2365686427  MPEG.ANL 001101  MPEG.ANL 001101   
1  2365686418  MPEG.ANL 001596  MPEG.ANL 001596   
2  2365686416  MPEG.ANL 001635  MPEG.ANL 001635   
3  2365686414  MPEG.ANL 001031  MPEG.ANL 001031   
4  2365686412  MPEG.ANL 001036  MPEG.ANL 001036   

                                          recordedBy preparations  \
0          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 3   
1  Sousa, Sandriel; Hernández, Luis; Rousseau, Gu...   Etanol - 1   
2      Sousa, Anny; Sousa, Sandriel; Hernández, Luis   Etanol - 1   
3          Beckman, Ruana; Pena, José; Souza, Raíssa   Etanol - 1   
4          Beckman, Ruana; Pena, José; Souza, Raíssa  Etanol - 17   

             eventDate    year  month   day eventRemarks     higherGeography  \
0  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN         Pará, Belém   
1  2018-08-15T00:00:00  2018.0    8.0  15.0          NaN  Maranhão, São Luís   
2  2019-02-12T00:00:00  2019.0    2.0  12.0          NaN    Maranhão, Caxias   
3  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN         Pará, Belém   
4  2017-08-30T00:00:00  2017.0    8.0  30.0          NaN         Pará, Belém   

  countryCode stateProvince    county              locality  decimalLatitude  \
0          BR          Pará     Belém               Mocambo         1.440694   
1          BR      Maranhão  São Luís        Fazenda Escola        -4.587222   
2          BR      Maranhão    Caxias  Santa Tereza Village        -4.899722   
3          BR          Pará     Belém               Mocambo         1.440694   
4          BR          Pará     Belém               Mocambo         1.440694   

   decimalLongitude typeStatus                 scientificName   kingdom  \
0        -48.411250   PARATYPE                    Pontoscolex  Animalia   
1        -44.208611        NaN  Liodrilus mendesi Righi, 1994  Animalia   
2        -43.470833        NaN  Liodrilus mendesi Righi, 1994  Animalia   
3        -48.411250   PARATYPE                    Pontoscolex  Animalia   
4        -48.411250   PARATYPE                    Pontoscolex  Animalia   

     phylum       class        order            family        genus  \
0  Annelida  Clitellata  Haplotaxida  Glossoscolecidae  Pontoscolex   
1  Annelida  Clitellata          NaN               NaN    Liodrilus   
2  Annelida  Clitellata          NaN               NaN    Liodrilus   
3  Annelida  Clitellata  Haplotaxida  Glossoscolecidae  Pontoscolex   
4  Annelida  Clitellata  Haplotaxida  Glossoscolecidae  Pontoscolex   

   genericName specificEpithet infraspecificEpithet taxonRank taxonomicStatus  \
0  Pontoscolex             NaN                  NaN     GENUS        DOUBTFUL   
1    Liodrilus         mendesi                  NaN   SPECIES        ACCEPTED   
2    Liodrilus         mendesi                  NaN   SPECIES        ACCEPTED   
3  Pontoscolex             NaN                  NaN     GENUS        DOUBTFUL   
4  Pontoscolex             NaN                  NaN     GENUS        DOUBTFUL   

            lastInterpreted  \
0  2023-09-07T09:19:05.952Z   
1  2023-09-07T09:19:05.949Z   
2  2023-09-07T09:19:05.937Z   
3  2023-09-07T09:19:05.946Z   
4  2023-09-07T09:19:05.946Z   

                                               issue  hasCoordinate  \
0  COORDINATE_ROUNDED;GEODETIC_DATUM_ASSUMED_WGS8...           True   
1  COORDINATE_ROUNDED;GEODETIC_DATUM_ASSUMED_WGS8...           True   
2  COORDINATE_ROUNDED;GEODETIC_DATUM_ASSUMED_WGS8...           True   
3  COORDINATE_ROUNDED;GEODETIC_DATUM_ASSUMED_WGS8...           True   
4  COORDINATE_ROUNDED;GEODETIC_DATUM_ASSUMED_WGS8...           True   

   hasGeospatialIssues  taxonKey  acceptedTaxonKey  kingdomKey  phylumKey  \
0                 True   2308740         2308740.0           1       42.0   
1                False   9512479         9512479.0           1       42.0   
2                False   9512479         9512479.0           1       42.0   
3                 True   2308740    

In [ ]:
for column in dados_sem_nan_e_fixos.columns:

  if len(dados_sem_nan_e_fixos[column].unique()) < 30:

    print(column)


year
month
eventRemarks
countryCode
stateProvince
typeStatus
kingdom
phylum
class
order
family
specificEpithet
infraspecificEpithet
taxonRank
taxonomicStatus
lastInterpreted
issue
hasCoordinate
hasGeospatialIssues
kingdomKey
phylumKey
classKey
orderKey
familyKey
speciesKey
species
lastParsed
repatriated
level0Gid
level0Name
level1Gid
level1Name
iucnRedListCategory
